
specVersion: 1.0.0
name: terra-subql-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node-cosmos'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your Cosmos based
  SubQuery project
repository: https://github.com/subquery/terra-subql-starter
schema:
  file: ./schema.graphql
network:
  chainId: juno-1
  endpoint: https://rpc-juno.itastakers.com/

dataSources:
  - kind: cosmos/Runtime
    startBlock: 3000000
    #chainTypes:
    #  cosmos.slashing.v1beta1:
    #    file: "./proto/cosmos/slashing/v1beta1/tx.proto"
    #    messages:
    #     - "MsgUnjail"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: cosmos/BlockHandler
        - handler: handleTransaction
          kind: cosmos/TransactionHandler
        - handler: handleEvent
          kind: cosmos/EventHandler
          filter:
            type: execute
            messageFilter:
              type: "/cosmwasm.wasm.v1.MsgExecuteContract"
        - handler: handleMessage
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
