specVersion: "0.3.0"

name: "subqlstarter-terra"
version: "0.0.0"
description: ""
repository: "https://github.com/stwiname/subqlstarter-terra"

schema:
  file: "./schema.graphql"

network:
  endpoint: https://bombay.stakesystems.io
  chainId: bombay-12
  dictionary: dictionaryxxxx

dataSources:
  - kind: terra/Runtime
    startBlock: 6000000
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: terra/BlockHandler
        - handler: handleTransferEvent
          kind: terra/EventHandler
          filter:
            type: transfer
